apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pgsql-backup-demo-
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: backup
        templateRef:
          name: pgsql-backup-minio
          template: backup
        arguments:
          parameters:
          - name: pg-host
            value: postgres.postgres.svc.cluster.local
          - name: pg-database
            value: postgres
          - name: pg-user
            value: postgres
          - name: bucket
            value: pgsql-backups
