apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: minio-upload-demo-
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: upload
        templateRef:
          name: minio-upload
          template: upload
        arguments:
          parameters:
          - name: bucket
            value: demo-uploads
          artifacts:
          - name: data
            git:
              repo: https://github.com/octocat/Hello-World.git
              depth: 1
